version: "3.10"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
#      - ./rabbitmq-internal/etc/:/etc/rabbitmq/
      - ./rabbitmq-internal/data:/var/lib/rabbitmq/
      - ./rabbitmq-internal/logs:/var/log/rabbitmq/
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge